config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :jobs_boards, only: [:new, :create, :show, :index]
  root 'jobs_boards#index'

  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/jobs_board.rb
# == Schema Information
#
# Table name: jobs_boards
#
#  id          :integer          not null, primary key
#  keyword     :string
#  description :string
#  user_id     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
# Indexes
#
#  index_jobs_boards_on_keyword  (keyword)
#  index_jobs_boards_on_user_id  (user_id)
#

class JobsBoard < ApplicationRecord
  belongs_to :user
  has_many :postings, dependent: :destroy

  validates_presence_of :keyword, :description
end

app/models/posting.rb
# == Schema Information
#
# Table name: postings
#
#  id            :integer          not null, primary key
#  headline      :text
#  body          :text
#  user_id       :integer
#  jobs_board_id :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_postings_on_headline       (headline)
#  index_postings_on_jobs_board_id  (jobs_board_id)
#  index_postings_on_user_id        (user_id)
#

class Posting < ApplicationRecord
  belongs_to :user
  belongs_to :jobs_board

  validates :headline, presence: true, length: {minimum: 2, maximum: 80}
  validates :body, presence: true, length: {minimum: 2, maximum: 1000}

  after_create_commit { PostingBroadcastJob.perform_later(self) }

  def timestamp
    created_at.strftime('%H:%M:%S %d %B %Y')
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default("0"), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :jobs_boards, dependent: :destroy
  has_many :postings, dependent: :destroy

  def name
    email.split('@')[0]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/jobs_boards_controller.rb
class JobsBoardsController < ApplicationController
  def index
    @jobs_boards = JobsBoard.all
  end

  def new
    @jobs_board = JobsBoard.new
  end

  def create
    @jobs_board = current_user.jobs_boards.build(jobs_board_params)
    if @jobs_board.save
      flash[:success] = 'Jobs board added!'
    else
      render 'new' and return
    end
    redirect_to jobs_board_path(@jobs_board)
  end

  def show
    @jobs_board = JobsBoard.includes(:postings).find_by(id: params[:id])
    @posting = Posting.new
  end

  private
  def jobs_board_params
    params.require(:jobs_board).permit(:keyword, :description)
  end
end

app/controllers/posting_controller.rb
class PostingController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_channels_helper.rb
module JobsChannelsHelper
end

app/views/jobs_boards/_jobs_board.html.erb
<li><%= link_to "Enter #{jobs_board.keyword}", jobs_board_path(jobs_board) %> - <%= jobs_board.description %> </li>

app/views/jobs_boards/index.html.erb
<h1>Jobs boards</h1>

<p class="lead"><%= link_to 'New jobs board', new_jobs_board_path, class: 'btn btn-primary' %></p>

<ul>
  <%= render @jobs_boards %>
</ul>

app/views/jobs_boards/new.html.erb
<h1>Add jobs board</h1>

<%= form_for @jobs_board, html: {class: "form-horizontal new_jobs_board"} do |f| %>
    <div class="form-group">
      <%= f.label :keyword, class: 'col-md-2 control-label' %>
      <div class="col-md-8">
        <%= f.text_field :keyword, autofocus: true, class: 'form-control' %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :description, class: 'col-md-2 control-label' %>
      <div class="col-md-8">
        <%= f.text_field :description, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.submit "Add Board", class: 'btn btn-primary' %>
      </div>
    </div>
<% end %>

app/views/jobs_boards/show.html.erb
<div class="row">
  <div class="col-md-8">
    <h1><%= @jobs_board.keyword %> - <%= @jobs_board.description %> </h1>
  </div>
  <div class="col-md-4 text-muted" id="connection_status">
    [UNKNOWN STATUS]
  </div>
</div>

<%= form_for @posting, url: '#', html: {class: "form-horizontal new_posting"} do |f| %>
    <div class="form-group">
      <%= f.label :headline, class: 'col-md-2 control-label' %>
      <div class="col-md-8">
        <%= f.text_field :headline, class: 'form-control' %>
      </div>
      <small class="text-muted">From 2 to 80 characters</small>
    </div>
    <div class="form-group">
      <%= f.label :body, class: 'col-md-2 control-label' %>
      <div class="col-md-8">
      <%= f.text_area :body, class: 'form-control' %>
      </div>
      <small class="text-muted">From 2 to 1000 characters</small>
    </div>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.submit "Post", class: 'btn btn-primary btn-lg' %>
      </div>
    </div>
<% end %>

<div id="postings" data-jobs-board-id="<%= @jobs_board.id %>">
  <%= render @jobs_board.postings.reverse_order %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AsyncJobs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/postings/_posting.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <div class="panel-title">
      <%= posting.headline %>
    </div>
  </div>
  <div class="panel-body">
    <%= posting.body %>
  </div>
  <div class="panel-footer">
    <%= posting.user.name %> at <%= posting.timestamp %>
  </div>
</div>